rules:
  - name: regex_kek
    type: tcp::regex
    args:
      - "ke?k"

  - name: contains_attack
    type: tcp::contains
    args:
      - "attack"

  - name: ingress_attack
    type: tcp::ingress::contains
    args:
      - "attack"

  - name: ingress_not_contains_legit
    type: tcp::ingress::not::contains
    args:
      - "legit"

  - name: http_ingress_json_kek_not_contains_legit
    type: http::ingress::not::json::contains
    field: kek
    args:
      - "legit"

services:
  - name: test tcp
    type: tcp
    listen: 0.0.0.0:1337
    target: 127.0.0.1:1338
    filters:
      - rule: regex_kek
        verdict: inc::keks
      - rule: egress
        verdict: "alert::show keks"
      - rule: ingress_attack
        verdict: inc::attacks
      - rule: egress
        verdict: "alert::show attacks"

  - name: test http
    type: http
    listen: 0.0.0.0:5001
    target: 127.0.0.1:5000
    filters:
      - rule: ingress
        verdict: "alert::ingress!"
      - rule: http_ingress_json_kek_not_contains_legit
        verdict: drop
