rules:
  ####### TCP RULES ########
  - name: regex_kek
    type: tcp::regex
    args:
      - "ke?k"

  - name: contains_attack
    type: tcp::contains
    args:
      - "attack"

  - name: ingress_not_contains_legit
    type: tcp::ingress::not::contains
    args:
      - "legit"

  - name: volgactf_flag
    type: tcp::volgactf_flag
    args:
      - "JCPOmYvE0bRQ4t6B-yu7cz3dp8F1IVWeXgn5AwkZfqa9_UxDThjKNiMlSL2GHosr."
  ######## END TCP RULES #########


  ######## HTTP RULES #########
  - name: http_form_username_contains_admin
    type: http::form::array::any::contains
    field: username
    args:
      - "admi"

  - name: http_body_contains_pt
    type: http::ingress::body::contains
    args:
      - "../"

  - name: curl_request
    type: http::headers::any::icontains
    field: "User-Agent"
    args:
      - "cUrl"

  - name: requests
    type: http::headers::any::contains
    field: "User-Agent"
    args:
      - "python-requests"

  - name: not_requests_2184
    type: http::ingress::not::headers::contains
    field: "User-Agent"
    args:
      - "python-requests/2.18.4"
  ######## END HTTP RULES #########

services:
  - name: test tcp
    type: tcp
    listen: 0.0.0.0:1337
    target: 127.0.0.1:1338
    filters:
      - rule: regex_kek
        verdict: inc::keks
      - rule: egress
        verdict: "alert::show keks"
      - rule: contains_attack
        alert: true
        verdict: drop

  - name: test http
    type: http
    listen: 0.0.0.0:5001
    target: 127.0.0.1:5000
    request_timeout: 10s
    filters:
      - rule: ingress
        verdict: "alert::ingress"
      - rule: http_body_contains_pt
        alert: true
        verdict: "drop"
      - rule: http_form_username_contains_admin
        verdict: "alert::admin in form username"
      - rule: curl_request
        verdict: "alert::curl request"
      - rule: requests
        verdict: "alert::requests"
      - rule: not_requests_2184
        verdict: "alert::not requests 2.18.4"

web:
  username: admin
  password: 1234
