rules:
  ####### TCP RULES ########
  - name: regex_kek
    type: regex
    args:
      - "ke?k"

  - name: contains_attack
    type: contains
    args:
      - "attack"

  - name: ingress_not_contains_legit
    type: ingress::not::contains
    args:
      - "legit"

  ######## END TCP RULES #########


  ######## HTTP RULES #########
  - name: http_form_username_contains_admin
    type: form::any::contains
    field: username
    args:
      - "admi"

  - name: http_body_contains_pt
    type: ingress::body::contains
    args:
      - "../"

  - name: curl_request
    type: headers::any::icontains
    field: "User-Agent"
    args:
      - "cUrl"

  - name: requests
    type: headers::any::contains
    field: "User-Agent"
    args:
      - "python-requests"

  - name: not_requests_2184
    type: ingress::not::headers::contains
    field: "User-Agent"
    args:
      - "python-requests/2.18.4"

  ######## END HTTP RULES #########

services:
  - name: test tcp
    type: tcp
    listen: 0.0.0.0:1337
    target: 127.0.0.1:1338
    filters:
      - rule: regex_kek
        verdict: inc::keks
      - rule: egress
        verdict: "alert::show keks"
      - rule: contains_attack
        alert: true
        verdict: drop

  - name: test http -> http
    type: http
    listen: 0.0.0.0:5001
    target: https://pomo-mondreganto.me
    request_timeout: 10s
    filters:
      # dummy verdict.
      - rule: ingress
      - rule: ingress
        verdict: "alert::ingress"
      - rule: http_body_contains_pt
        alert: true
        verdict: "drop"
      - rule: http_form_username_contains_admin
        verdict: "alert::admin in form username"
      - rule: curl_request
        verdict: "alert::curl request"
      - rule: requests
        verdict: "alert::requests"
      - rule: not_requests_2184
        verdict: "alert::not requests 2.18.4"

  - name: test https -> https
    type: http
    listen: 0.0.0.0:5002
    target: https://pomo-mondreganto.me
    request_timeout: 10s
    tls:
      cert: testdata/tls/cert.pem
      key: testdata/tls/key.pem
    filters:
      # dummy verdict.
      - rule: ingress
      - rule: ingress
        verdict: "alert::ingress"
      - rule: http_body_contains_pt
        alert: true
        verdict: "drop"
      - rule: http_form_username_contains_admin
        verdict: "alert::admin in form username"
      - rule: curl_request
        verdict: "alert::curl request"
      - rule: requests
        verdict: "alert::requests"
      - rule: not_requests_2184
        verdict: "alert::not requests 2.18.4"

  - name: test https -> http
    type: http
    listen: 0.0.0.0:5003
    target: http://lnip.su
    request_timeout: 10s
    tls:
      cert: testdata/tls/cert.pem
      key: testdata/tls/key.pem
    filters:
      # dummy verdict.
      - rule: ingress
      - rule: ingress
        verdict: "alert::ingress"
      - rule: http_body_contains_pt
        alert: true
        verdict: "drop"
      - rule: http_form_username_contains_admin
        verdict: "alert::admin in form username"
      - rule: curl_request
        verdict: "alert::curl request"
      - rule: requests
        verdict: "alert::requests"
      - rule: not_requests_2184
        verdict: "alert::not requests 2.18.4"


web:
  username: admin
  password: 1234

mongol:
  addr: 127.0.0.1:5139
