name: main
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Run tests
        run: go test -race ./...

      - name: Install front deps
        working-directory: front
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Build front
        uses: borales/actions-yarn@v2.0.0
        working-directory: front
        with:
          cmd: build

      - name: Release placeholder
        run: ls front/dist
