name: release
on: push
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Run tests
        run: go test -race ./...

      - name: Set up Node 13
        uses: actions/setup-node@v2
        with:
          node-version: '13'
      - name: Build front
        working-directory: front
        run: yarn install && yarn build

      - name: Release placeholder
        run: ls front/dist
